### ISSUE TITLE
rake aborted

### ISSUE THREAD

**Issue by bganicky** [pragdave/codex#1]
Hi, I tried "rake all" command and it ended with this error:
    (in /home/besh/Dev/codex)
    rake aborted!
    Don't know how to build task 'all'

```
(See full trace by running task with --trace)
```

And with the trace:
    rake aborted!
    Don't know how to build task 'all'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1728:in `[]'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2050:in`invoke_task'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
    /usr/bin/rake:19:in `load'
    /usr/bin/rake:19

**Comment by zeeshangulzar** [comment]
I am facing sam issue for an older app. Any solution yet?

**Comment by pragdave** [comment]
It looks like a bunch of things have changed over the last 8 years.

I don't have the time to maintain this, now. If you'd like to generate a PR I'd love to look at it.


Dave
